This error was resolved after i created a new env and installed jupyter in it. 
Steps to create [new environment](https://github.com/akanksha21singh/AnacondaSolutions/blob/main/creating%20new%20env%20in%20anaconda). 
