This error was resolved after i created a new env and installed jupyter in it. 
Steps to create new environment. 
